version: '3'
services:
  hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443        
      - 4444:4444
  node-chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=10
    ports:
      - 5901:5900


